// iopll.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module iopll (
		input  wire  refclk,   //  refclk.clk,   The reference clock source that drives the I/O PLL.
		input  wire  rst,      //   reset.reset, The asynchronous reset port for the output clocks. Drive this port high to reset all output clocks to the value of 0.
		output wire  outclk_0  // outclk0.clk,   Output clock Channel 0 from I/O PLL.
	);

	iopll_altera_iopll_2100_rbeghoa iopll_0 (
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
